export const products = [
  {
    id: 1,
    name: "Iris 1 mounth",
    description: "Lentes de Contato Acuvue Oasys",
    old_price: 172,
    newest_price: 154.8,
    installments: 5,
    unit_installment_price: 30.96,
    price: 147.06,
  },
  {
    id: 2,
    name: "Iris day",
    description: "Lentes de Contato Bioinfinity",
    old_price: 199,
    newest_price: 179.1,
    installments: 5,
    unit_installment_price: 35.82,
    price: 170.14,
  },
  {
    id: 3,
    name: "iris Softlens",
    description: "Lentes de contato Soflens 59",
    old_price: 104,
    newest_price: 88.4,
    installments: 2,
    unit_installment_price: 44.2,
    price: 83.98,
  },
  {
    id: 4,
    name: "Iris Hydraglyde",
    description: "Lentes de Contato Air iris Plus Hydraglyde",
    old_price: 176.65,
    newest_price: 158.99,
    installments: 5,
    unit_installment_price: 31.79,
    price: 151.04,
  },
];
