export const products = [
  {
    id: 1,
    name: "Iris Transition",
    description: "Lentes de Contato iris Transition",
    old_price: 676.65,
    newest_price: 590.99,
    installments: 5,
    unit_installment_price: 118.19,
    price: 550.49,
    url_image:
      "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSGxaoBJYibBfQEyb0FrYg9qkj4CjsaqYOkZb1h2IWAWgNIxdLf",
  },
  {
    id: 2,
    name: "Iris confort",
    description: "Lentes de contato Iris confort",
    old_price: 525.49,
    newest_price: 450.49,
    installments: 3,
    unit_installment_price: 150.16,
    price: 399.9,
    url_image: "images/lente-2.jpg",
  },
  {
    id: 3,
    name: "Iris 1 mounth",
    description: "Lentes de Contato Iris mounth",
    old_price: 235,
    newest_price: 154.8,
    installments: 5,
    unit_installment_price: 30.96,
    price: 147.06,
    url_image: "images/lente-1.jpg",
  },
  {
    id: 4,
    name: "Iris day",
    description: "Lentes de Contato Iris Day",
    old_price: 199,
    newest_price: 179.1,
    installments: 5,
    unit_installment_price: 35.82,
    price: 170.14,
    url_image: "images/lente-3.jpg",
  },
];
